[
    "Ancient",
    "Card Game",
    "City Building",
    "Civilization",
    "Economic",
    "Animals",
    "Economic",
    "Farming",
    "Bluffing",
    "Card Game",
    "Collectible Components",
    "Science Fiction",
    "Comic Book / Strip",
    "Fantasy",
    "Adventure",
    "Fantasy",
    "Fighting",
    "Horror",
    "Novel-based",
    "Adventure",
    "Card Game",
    "Collectible Components",
    "Fantasy",
    "Horror",
    "Novel-based",
    "Card Game",
    "Bluffing",
    "Deduction",
    "Movies / TV / Radio theme",
    "Political",
    "Science Fiction",
    "Space Exploration",
    "Spies/Secret Agents",
    "Exploration",
    "Maze",
    "Spies/Secret Agents",
    "Bluffing",
    "Card Game",
    "Fighting",
    "Humor",
    "Mafia",
    "Negotiation",
    "Party Game",
    "Economic",
    "Negotiation",
    "Card Game",
    "Deduction",
    "Party Game",
    "Spies/Secret Agents",
    "Word Game",
    "Card Game",
    "Deduction",
    "Spies/Secret Agents",
    "Word Game",
    "Deduction",
    "Party Game",
    "Bluffing",
    "Card Game",
    "Deduction",
    "Party Game",
    "Political",
    "Party Game",
    "Puzzle",
    "Trivia",
    "Word Game",
    "Adventure",
    "Card Game",
    "Fantasy",
    "Fighting",
    "Humor",
    "Card Game",
    "Pirates",
    "Bluffing",
    "Negotiation",
    "Political",
    "Post-Napoleonic",
    "Wargame",
    "World War I",
    "Card Game",
    "Medieval",
    "Card Game",
    "Medieval",
    "Action / Dexterity",
    "Adventure",
    "Dice",
    "Electronic",
    "Exploration",
    "Real-time",
    "Bluffing",
    "Deduction",
    "Party Game",
    "Card Game",
    "Economic",
    "Adventure",
    "Deduction",
    "Fighting",
    "Horror",
    "Novel-based",
    "Real-time",
    "Science Fiction",
    "Space Exploration",
    "Transportation",
    "Card Game",
    "World War I",
    "Card Game",
    "Deduction",
    "Memory",
    "Card Game",
    "Fantasy",
    "Movies / TV / Radio theme",
    "Novel-based",
    "Card Game",
    "Pirates",
    "Card Game",
    "Deduction",
    "Renaissance",
    "Adventure",
    "Exploration",
    "Fantasy",
    "Fighting",
    "Miniatures",
    "Wargame",
    "World War II",
    "Card Game",
    "Real-time",
    "Card Game",
    "Economic",
    "Deduction",
    "Horror",
    "Murder/Mystery",
    "Party Game",
    "Bluffing",
    "Card Game",
    "Deduction",
    "Horror",
    "Party Game",
    "Bluffing",
    "Card Game",
    "Deduction",
    "Horror",
    "Party Game",
    "Medical",
    "Environmental",
    "Medical",
    "Environmental",
    "Exploration",
    "Medical",
    "Economic",
    "Negotiation",
    "Real-time",
    "Card Game",
    "Print & Play",
    "Word Game",
    "City Building",
    "Economic",
    "Farming",
    "Card Game",
    "Fantasy",
    "Video Game Theme",
    "Card Game",
    "Number",
    "Bluffing",
    "Card Game",
    "Deduction",
    "Negotiation",
    "Party Game",
    "Science Fiction",
    "Spies/Secret Agents",
    "Adventure",
    "Exploration",
    "Fighting",
    "Novel-based",
    "Territory Building",
    "Card Game",
    "Fantasy",
    "Bluffing",
    "Card Game",
    "Humor",
    "Medieval",
    "Negotiation",
    "Novel-based",
    "Party Game",
    "Electronic",
    "Real-time",
    "Science Fiction",
    "Space Exploration",
    "Age of Reason",
    "Environmental",
    "Fantasy",
    "Fighting",
    "Mythology",
    "Renaissance",
    "Territory Building",
    "Economic",
    "Environmental",
    "Industry / Manufacturing",
    "Science Fiction",
    "Space Exploration",
    "Territory Building",
    "Trains",
    "Economic",
    "Farming",
    "Party Game",
    "Trivia",
    "Adventure",
    "Fantasy",
    "Fighting",
    "Miniatures",
    "Video Game Theme",
    "Real-time",
    "Science Fiction",
    "Video Game Theme"
]